USE [mSCOA_Vault]
GO


Alter Table [Lookup_ISU_Vault]
Add Id_ISU_Vault Int Identity(1, 1)
Go


ALTER TABLE [dbo].[Lookup_ISU_Vault] ADD  CONSTRAINT [PK_Lookup_ISU_Vault] PRIMARY KEY CLUSTERED 
(
	[Id_ISU_Vault] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

